### ISSUE TITLE
FE Feat/todo : food archieve page

### ISSUE THREAD

**Issue by YujunSun0** [codestates-seb/seb43_main_004#17]
## 설명
음식 아카이브 페이지 목업 + 기능
 ## 할 일
- [x] 스타일 가이드에 따른 페이지 목업
- [x] 검색 기능 구현 (검색하면 입력한 키워드 강조효과, 레벤슈타인 거리를 이용한 유사도 계산)
- [x] 페이지 설명 모달 구현
- [x] 리덕스 툴킷을 이용하여 상태 전역으로 관리하기

## 예상 소요 시간 / 실제 소요 시간
5h
