### ISSUE TITLE
FE Feat/todo : pagination component

### ISSUE THREAD

**Issue by YujunSun0** [codestates-seb/seb43_main_004#20]
## 설명
공용 컴포넌트인 페이지네이션 제작

## 할 일
- [x] react-js-pagination을 이용한 컴포넌트 제작
- [x] 스타일 가이드에 맞게 스타일링
- [x] 다른 컴포넌트에서 사용 가능하게 props로 받는 변수 타입 설정

## 예상 소요 시간 / 실제 소요 시간
1h
