### ISSUE TITLE
FE Feat/todo : header component

### ISSUE THREAD

**Issue by moondrop0816** [codestates-seb/seb43_main_004#24]
## 설명
헤더 컴포넌트

## 할 일
- [x] 헤더 컴포넌트 생성
- [x] 기본 ui 및 반응형 구현
- [x] (수정) 헤더 사이즈 조정
- [x] 위치 및 포지션 수정
- [x] 라우터 주소 정리되면 메뉴별 액티브 처리
