### ISSUE TITLE
FE Feat/todo : diary feature

### ISSUE THREAD

**Issue by YujunSun0** [codestates-seb/seb43_main_004#34]
## 설명
일기 전체 조회 페이지 기능
## 할 일
- [x] 통계에서 사용자의 표준섭취량과 지난주의 영양소 데이터를 비교하여 부족, 적정, 과다로 분류
- [x] 캘린더의 특정 일을 클릭했을 때, 해당하는 날의 일기 페이지로 이동(get)
- [x] 캘린더의 특정 일을 클릭했을 때, 해당 일에 작성한 일기가 없다면 생성하기 (post)
--------------------------------------------------------------------------------------------
우선순위 낮은 기능
- [x] 이모지를 데이터로 받으면 캘린더에 표시
