### ISSUE TITLE
BE Feat/todo : businessException

### ISSUE THREAD

**Issue by 021Skyfall** [codestates-seb/seb43_main_004#4]
## 설명
전체 비지니스 에러 핸들링
다 같이 작업해야할 듯

## 할일
1. [x] : 글로벌 익셉션 핸들러 작성
2. [x] : 익셉션 핸들러 메서드 작성
3. [x] : 비지니스 로직 익셉션 클래스 구현
4. [x] : 에러 코드 클래스 구현

## 예상 소요 시간 / 실제 소요 시간
?

**Comment by 021Skyfall** [comment]
비지니스 익셉션 핸들러 구현 완료,
익셉션 코드는 추후 필요할 때 마다 추가할 것

AOP 핸들링 완료
